[package]
name = "turborepo-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
dunce = "1.0.3"
lazy_static = "1.4.0"
tar = "0.4.38"
thiserror = "1.0.38"
turborepo-api-client = { path = "../turborepo-api-client" }
zstd = "0.12.3"
