[package]
name = "turborepo-api-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
anyhow = "1.0.69"
chrono = { version = "0.4.23", features = ["serde"] }
lazy_static = "1.4.0"
reqwest = { version = "0.11.14", default_features = false, features = ["json"] }
rustc_version_runtime = "0.2.1"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = { workspace = true }
tokio = "1.25.0"
